steps:
# Dockerize the app and tag
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/homedepot-342320/vinkumorg/chatapp1:v3', '.' ]
# Push docker images to Artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east1-docker.pkg.dev/homedepot-342320/vinkumorg/chatapp1:v3' ]
# Authentication to Artifact registry
- name: gcr.io/cloud-builders/gcloud
  args: ['auth', 'configure-docker', 'us-east1-docker.pkg.dev']
# Deploy container image to Cloud Run
- name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', 'chatapp1', '--image', 'us-east1-docker.pkg.dev/homedepot-342320/vinkumorg/chatapp1:v3', '--region', 'us-east1','--min-instances','1','--max-instances','10','--allow-unauthenticated']
images:
- us-east1-docker.pkg.dev/homedepot-342320/vinkumorg/chatapp1:v3

# # Test
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'pull', 'us-central1-docker.pkg.dev/bcs-observations-poc/observations-repository/observations-api:v1' ]
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['auth', 'list']
# # Deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --image=us-central1-docker.pkg.dev/bcs-observations-poc/observations-repository/observations-api:v1
#   - --location=us-central1
#   - --cluster=bcs-observations-poc-gke
