apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: chatapp-
build:
  artifacts:  
  - image: gcr.io/k8s-skaffold/example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
